import type { Match, Player, Season, Story, Team } from './types'

export const initialSeasons: Season[] = [
  {
    id: 1,
    city: 'Antalya',
    year: 2026,
    name: 'INTERNATIONAL CORPORATE CUP Sezonu',
    fullName: 'Antalya 2026 INTERNATIONAL CORPORATE CUP Sezonu',
    parentSeasonId: null,
    isActive: true,
  },
  {
    id: 2,
    city: 'İstanbul',
    year: 2026,
    name: 'Corporate Champions League Sezonu',
    fullName: 'İstanbul 2026 Corporate Champions League Sezonu',
    parentSeasonId: null,
    isActive: true,
  },
  {
    id: 3,
    city: 'Antalya',
    year: 2025,
    name: 'INTERNATIONAL CORPORATE CUP Sezonu',
    fullName: 'Antalya 2025 INTERNATIONAL CORPORATE CUP Sezonu',
    parentSeasonId: null,
    isActive: false,
  },
  {
    id: 4,
    city: 'Antalya',
    year: 2024,
    name: 'INTERNATIONAL CORPORATE CUP Sezonu',
    fullName: 'Antalya 2024 INTERNATIONAL CORPORATE CUP Sezonu',
    parentSeasonId: null,
    isActive: false,
  },
  {
    id: 5,
    city: 'Antalya',
    year: 2023,
    name: 'INTERNATIONAL CORPORATE CUP Sezonu',
    fullName: 'Antalya 2023 INTERNATIONAL CORPORATE CUP Sezonu',
    parentSeasonId: null,
    isActive: false,
  },
  {
    id: 6,
    city: 'Antalya',
    year: 2022,
    name: 'INTERNATIONAL CORPORATE CUP Sezonu',
    fullName: 'Antalya 2022 INTERNATIONAL CORPORATE CUP Sezonu',
    isActive: false,
  },
]

export const initialTeams: Team[] = [
  {
    id: 1,
    name: 'NOVA FC',
    shortName: 'NOV',
    countryCode: 'TR',
    countryName: 'Turkey',
    color: '#63e35b',
    secondaryColor: '#071525',
    managerName: 'Mehmet Özkan',
    coachName: 'Bülent Korkut',
    bio: 'Founding member club known for aggressive pressing and fast transitions.',
    tournamentFormat: 'Champions Cup',
    groupName: 'Group A',
    played: 3,
    goalDifference: 6,
    points: 9,
    isActive: true,
  },
  {
    id: 2,
    name: 'MARMARA',
    shortName: 'MAR',
    countryCode: 'TR',
    countryName: 'Turkey',
    color: '#3f76ff',
    secondaryColor: '#ffffff',
    managerName: 'Selim Vardar',
    coachName: 'Okan Koç',
    bio: 'Reigning cup finalists with a balanced tactical setup and disciplined defensive record.',
    tournamentFormat: 'Champions Cup',
    groupName: 'Group A',
    played: 3,
    goalDifference: 2,
    points: 6,
    isActive: true,
  },
  {
    id: 3,
    name: 'UNION',
    shortName: 'UNI',
    countryCode: 'DE',
    countryName: 'Germany',
    color: '#f2c230',
    secondaryColor: '#1a1a1a',
    managerName: 'Hans Becker',
    coachName: 'Lukas Meyer',
    bio: 'Dynamic corporate squad featuring international players across European offices.',
    tournamentFormat: 'Champions Cup',
    groupName: 'Group B',
    played: 3,
    goalDifference: -1,
    points: 3,
    isActive: true,
  },
  {
    id: 4,
    name: 'NORTHSIDE',
    shortName: 'NOR',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    color: '#8c9bad',
    secondaryColor: '#ffffff',
    managerName: 'David Sterling',
    coachName: 'Paul Gallagher',
    bio: 'Fast-paced counter-attacking side from the northern district tech sector.',
    tournamentFormat: 'Challenge Cup',
    groupName: 'Group B',
    played: 3,
    goalDifference: -7,
    points: 0,
    isActive: true,
  },
  {
    id: 5,
    name: 'ATLAS SK',
    shortName: 'ATL',
    countryCode: 'NL',
    countryName: 'Netherlands',
    color: '#ff5c5c',
    secondaryColor: '#071525',
    managerName: 'Robin van Dijk',
    coachName: 'Kees Jansen',
    bio: 'Dutch logistics tech club with possession-dominant football philosophy.',
    tournamentFormat: 'Champions Cup',
    groupName: 'Group A',
    played: 2,
    goalDifference: 1,
    points: 4,
    isActive: true,
  },
  {
    id: 6,
    name: 'BOSPHORUS',
    shortName: 'BOS',
    countryCode: 'TR',
    countryName: 'Turkey',
    color: '#00d2d3',
    secondaryColor: '#071525',
    managerName: 'Cemil Demir',
    coachName: 'Ali Tandoğan',
    bio: 'Historic shipping sector team known for set-piece efficiency and aerial dominance.',
    tournamentFormat: 'Challenge Cup',
    groupName: 'Group A',
    played: 2,
    goalDifference: -1,
    points: 1,
    isActive: true,
  },
]

export const initialPlayers: Player[] = [
  // NOVA FC (5 players)
  { id: 101, teamId: 1, teamName: 'NOVA FC', fullName: 'Emre Yılmaz', shirtNumber: 10, position: 'forward', birthYear: 1996, nationality: 'TR', isCaptain: true, activeSeasonIds: [1, 4], goals: 4, assists: 2 },
  { id: 102, teamId: 1, teamName: 'NOVA FC', fullName: 'Can Demir', shirtNumber: 7, position: 'midfielder', birthYear: 1998, nationality: 'TR', activeSeasonIds: [1], goals: 2, assists: 3 },
  { id: 103, teamId: 1, teamName: 'NOVA FC', fullName: 'Burak Kaya', shirtNumber: 4, position: 'defender', birthYear: 1995, nationality: 'TR', activeSeasonIds: [1, 3], goals: 0, assists: 1 },
  { id: 104, teamId: 1, teamName: 'NOVA FC', fullName: 'Mert Aksoy', shirtNumber: 1, position: 'goalkeeper', birthYear: 1997, nationality: 'TR', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 105, teamId: 1, teamName: 'NOVA FC', fullName: 'Sarp Güven', shirtNumber: 8, position: 'midfielder', birthYear: 1999, nationality: 'TR', activeSeasonIds: [1], goals: 1, assists: 1 },

  // MARMARA (5 players)
  { id: 201, teamId: 2, teamName: 'MARMARA', fullName: 'Tolga Çelik', shirtNumber: 9, position: 'forward', birthYear: 1994, nationality: 'TR', isCaptain: true, activeSeasonIds: [1, 3, 4], goals: 3, assists: 1 },
  { id: 202, teamId: 2, teamName: 'MARMARA', fullName: 'Oğuzhan Kurt', shirtNumber: 8, position: 'midfielder', birthYear: 1999, nationality: 'TR', activeSeasonIds: [1], goals: 1, assists: 2 },
  { id: 203, teamId: 2, teamName: 'MARMARA', fullName: 'Serdar Şahin', shirtNumber: 3, position: 'defender', birthYear: 1993, nationality: 'TR', activeSeasonIds: [1, 3], goals: 0, assists: 0 },
  { id: 204, teamId: 2, teamName: 'MARMARA', fullName: 'Alican Polat', shirtNumber: 1, position: 'goalkeeper', birthYear: 2000, nationality: 'TR', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 205, teamId: 2, teamName: 'MARMARA', fullName: 'Kadir Baran', shirtNumber: 5, position: 'defender', birthYear: 1996, nationality: 'TR', activeSeasonIds: [1], goals: 0, assists: 0 },

  // UNION (5 players)
  { id: 301, teamId: 3, teamName: 'UNION', fullName: 'Kerem Aydın', shirtNumber: 11, position: 'forward', birthYear: 1997, nationality: 'DE', isCaptain: true, activeSeasonIds: [1, 2], goals: 2, assists: 0 },
  { id: 302, teamId: 3, teamName: 'UNION', fullName: 'Sinan Öztürk', shirtNumber: 6, position: 'midfielder', birthYear: 1995, nationality: 'DE', activeSeasonIds: [1], goals: 1, assists: 1 },
  { id: 303, teamId: 3, teamName: 'UNION', fullName: 'Hakan Koç', shirtNumber: 5, position: 'defender', birthYear: 1992, nationality: 'DE', activeSeasonIds: [1, 4], goals: 0, assists: 0 },
  { id: 304, teamId: 3, teamName: 'UNION', fullName: 'Markus Weber', shirtNumber: 1, position: 'goalkeeper', birthYear: 1994, nationality: 'DE', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 305, teamId: 3, teamName: 'UNION', fullName: 'Felix Schneider', shirtNumber: 4, position: 'defender', birthYear: 1998, nationality: 'DE', activeSeasonIds: [1], goals: 0, assists: 0 },

  // NORTHSIDE (5 players)
  { id: 401, teamId: 4, teamName: 'NORTHSIDE', fullName: 'Deniz Arslan', shirtNumber: 10, position: 'midfielder', birthYear: 1998, nationality: 'GB', isCaptain: true, activeSeasonIds: [1], goals: 1, assists: 1 },
  { id: 402, teamId: 4, teamName: 'NORTHSIDE', fullName: 'Alper Yıldız', shirtNumber: 9, position: 'forward', birthYear: 1996, nationality: 'GB', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 403, teamId: 4, teamName: 'NORTHSIDE', fullName: 'James Wilson', shirtNumber: 1, position: 'goalkeeper', birthYear: 1995, nationality: 'GB', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 404, teamId: 4, teamName: 'NORTHSIDE', fullName: 'Harry Davies', shirtNumber: 3, position: 'defender', birthYear: 1997, nationality: 'GB', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 405, teamId: 4, teamName: 'NORTHSIDE', fullName: 'Oliver Brown', shirtNumber: 7, position: 'forward', birthYear: 1999, nationality: 'GB', activeSeasonIds: [1], goals: 0, assists: 0 },

  // ATLAS SK (5 players)
  { id: 501, teamId: 5, teamName: 'ATLAS SK', fullName: 'Volkan Karaca', shirtNumber: 10, position: 'forward', birthYear: 1995, nationality: 'NL', isCaptain: true, activeSeasonIds: [1, 3], goals: 2, assists: 1 },
  { id: 502, teamId: 5, teamName: 'ATLAS SK', fullName: 'Cem Güler', shirtNumber: 8, position: 'midfielder', birthYear: 1997, nationality: 'NL', activeSeasonIds: [1], goals: 1, assists: 1 },
  { id: 503, teamId: 5, teamName: 'ATLAS SK', fullName: 'Lars de Jong', shirtNumber: 1, position: 'goalkeeper', birthYear: 1996, nationality: 'NL', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 504, teamId: 5, teamName: 'ATLAS SK', fullName: 'Daan Meijer', shirtNumber: 4, position: 'defender', birthYear: 1994, nationality: 'NL', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 505, teamId: 5, teamName: 'ATLAS SK', fullName: 'Bram Bakker', shirtNumber: 6, position: 'midfielder', birthYear: 1998, nationality: 'NL', activeSeasonIds: [1], goals: 0, assists: 0 },

  // BOSPHORUS (5 players)
  { id: 601, teamId: 6, teamName: 'BOSPHORUS', fullName: 'Kaan Tekin', shirtNumber: 9, position: 'forward', birthYear: 1996, nationality: 'TR', isCaptain: true, activeSeasonIds: [1], goals: 1, assists: 0 },
  { id: 602, teamId: 6, teamName: 'BOSPHORUS', fullName: 'Onur Eren', shirtNumber: 4, position: 'defender', birthYear: 1994, nationality: 'TR', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 603, teamId: 6, teamName: 'BOSPHORUS', fullName: 'Tayfun Balcı', shirtNumber: 1, position: 'goalkeeper', birthYear: 1995, nationality: 'TR', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 604, teamId: 6, teamName: 'BOSPHORUS', fullName: 'Murat Doğan', shirtNumber: 7, position: 'midfielder', birthYear: 1997, nationality: 'TR', activeSeasonIds: [1], goals: 0, assists: 0 },
  { id: 605, teamId: 6, teamName: 'BOSPHORUS', fullName: 'Eren Can', shirtNumber: 11, position: 'forward', birthYear: 1999, nationality: 'TR', activeSeasonIds: [1], goals: 0, assists: 0 },
]


export const initialMatches: Match[] = [
  {
    id: 1,
    home: 'NOVA FC',
    away: 'ATLAS SK',
    stage: 'Group A',
    date: '16 Aug',
    time: '20:30',
    venue: 'Central Arena',
    referee: 'Mehmet Ali Yılmaz',
    matchStatus: 'scheduled',
    status: 'Scheduled',
    events: [],
  },
  {
    id: 2,
    home: 'MARMARA',
    away: 'BOSPHORUS',
    stage: 'Group A',
    date: '15 Aug',
    time: '19:00',
    venue: 'Riverside Pitch',
    referee: 'Cüneyt Akın',
    homeScore: 2,
    awayScore: 1,
    matchStatus: 'completed',
    status: 'Scheduled',
    events: [
      { id: 1, matchId: 2, teamName: 'MARMARA', playerName: 'Tolga Çelik', eventType: 'goal', minute: 18, notes: 'Right foot strike from edge of box' },
      { id: 2, matchId: 2, teamName: 'BOSPHORUS', playerName: 'Kaan Tekin', eventType: 'goal', minute: 44, notes: 'Header from corner kick' },
      { id: 3, matchId: 2, teamName: 'MARMARA', playerName: 'Oğuzhan Kurt', eventType: 'yellow_card', minute: 62 },
      { id: 4, matchId: 2, teamName: 'MARMARA', playerName: 'Tolga Çelik', eventType: 'goal', minute: 89, notes: 'Stoppage time winning volley' },
    ],
  },
  {
    id: 3,
    home: 'UNION',
    away: 'NORTHSIDE',
    stage: 'Group B',
    date: '15 Aug',
    time: '21:00',
    venue: 'Central Arena',
    referee: 'Ahmet Taşçı',
    homeScore: 0,
    awayScore: 0,
    matchStatus: 'completed',
    status: 'Scheduled',
    events: [
      { id: 5, matchId: 3, teamName: 'UNION', playerName: 'Hakan Koç', eventType: 'yellow_card', minute: 35 },
      { id: 6, matchId: 3, teamName: 'NORTHSIDE', playerName: 'Deniz Arslan', eventType: 'yellow_card', minute: 74 },
    ],
  },
  {
    id: 4,
    home: 'MARMARA',
    away: 'NOVA FC',
    stage: 'Group A',
    date: '18 Aug',
    time: '20:30',
    venue: 'Central Arena',
    referee: 'Serkan Çakar',
    matchStatus: 'scheduled',
    status: 'Scheduled',
    events: [],
  },
]

export const initialStories: Story[] = [
  {
    id: 1,
    title: 'A night decided in the final minute: Tolga Çelik seals dramatic Marmara victory',
    summary: 'In a tense, end-to-end clash at Riverside Pitch, a stoppage-time strike sealed all three points and a place in the last eight.',
    body: `The atmosphere under the floodlights at Riverside Pitch was electric as Marmara and Bosphorus battled for decisive Group A qualification points.

Marmara broke the deadlock in the 18th minute when striker Tolga Çelik unleashed a thunderous strike from the edge of the area following a clever flick from Oğuzhan Kurt.

Bosphorus responded with relentless intensity, leveling the score right before halftime as Kaan Tekin out-jumped the defense to head home from an inswinging corner.

With the match hanging in the balance and the referee preparing to signal additional time, Tolga struck again in the 89th minute, volleying home from close range to trigger ecstatic celebrations and send Marmara to second in Group A.`,
    category: 'match_report',
    status: 'Published',
    publishedAt: '15 Aug 2026',
    coverImageUrl: '/assets/ccl-celebration.png',
  },
  {
    id: 2,
    title: 'Quarter-final draw confirmed: Titans collide in Istanbul knockout stages',
    summary: 'The bracket is set for the CCL Cup knockout phase with thrilling matchups across Istanbul arenas.',
    body: `Following an unforgettable group stage marked by high drama and breakout performances, the official quarter-final draw for the CCL Cup 2026 season has been completed.

The standout tie of the round sees group leaders NOVA FC square off against perennial contenders Atlas SK in what promises to be an explosive contest at Central Arena.

Matches will kick off this weekend with video highlights and live statistics available directly on the CCL Cup platform.`,
    category: 'announcement',
    status: 'Published',
    publishedAt: '14 Aug 2026',
    coverImageUrl: '/assets/ccl-hero.png',
  },
  {
    id: 3,
    title: 'Meet the captains: voices and leadership from the pitch',
    summary: 'Captain interviews, dressing room insights, and tactical preparations ahead of matchday four.',
    body: `Leadership under pressure is what defines champions in the CCL Cup. We sat down with captains from Nova FC, Marmara, and Union to discuss tactical philosophies, squad mentality, and what it means to lead their teams under the lights.

"Every fixture in this tournament feels like a final," said Nova FC captain Emre Yılmaz. "The intensity is unmatched, and our preparation has to match the standard required."`,
    category: 'news',
    status: 'Published',
    publishedAt: '13 Aug 2026',
  },
  {
    id: 4,
    title: 'Training ground notes: Tactical shifts ahead of pivotal group clashes',
    summary: 'Exclusive insights into coach setups and set-piece drills heading into the weekend fixtures.',
    body: `Coaches across the league are adjusting tactical shapes as the tournament reaches its business end. From high-pressing defensive lines to rapid transitional counters, teams are leaving nothing to chance.`,
    category: 'news',
    status: 'Draft',
  },
]

