-- Update seasons and related tables to support all tournament formats, dynamic canvas, and direct storage

-- 1. Ensure columns exist on public.seasons
alter table public.seasons add column if not exists full_name text;
alter table public.seasons add column if not exists year smallint default 2026;
alter table public.seasons add column if not exists city text default 'Antalya';
alter table public.seasons add column if not exists season_type text default 'tournament';
alter table public.seasons add column if not exists team_count smallint default 8;
alter table public.seasons add column if not exists group_count smallint;
alter table public.seasons add column if not exists bracket jsonb;
alter table public.seasons add column if not exists league jsonb;
alter table public.seasons add column if not exists group_league jsonb;
alter table public.seasons add column if not exists parent_season_id bigint;

-- 2. Make legacy constraints nullable or flexible
alter table public.seasons alter column city_id drop not null;
alter table public.seasons alter column starts_on drop not null;
alter table public.seasons alter column ends_on drop not null;
alter table public.seasons alter column starts_on set default current_date;
alter table public.seasons alter column ends_on set default (current_date + interval '90 days');

-- 3. Change ID to generated by default (allows custom client IDs)
alter table public.seasons alter column id drop identity if exists;
alter table public.seasons alter column id add generated by default as identity;

-- 4. Enable RLS and permissive staff/anon policies for development
alter table public.seasons enable row level security;

drop policy if exists "seasons_all_access" on public.seasons;
create policy "seasons_all_access" on public.seasons for all using (true) with check (true);

drop policy if exists "teams_all_access" on public.teams;
create policy "teams_all_access" on public.teams for all using (true) with check (true);

drop policy if exists "players_all_access" on public.players;
create policy "players_all_access" on public.players for all using (true) with check (true);

drop policy if exists "matches_all_access" on public.matches;
create policy "matches_all_access" on public.matches for all using (true) with check (true);

drop policy if exists "articles_all_access" on public.articles;
create policy "articles_all_access" on public.articles for all using (true) with check (true);

-- 5. Ensure cities table has common cities
insert into public.cities (name, country_code)
values 
  ('Antalya', 'TR'),
  ('Istanbul', 'TR'),
  ('Izmir', 'TR'),
  ('Ankara', 'TR'),
  ('Bursa', 'TR')
on conflict (name) do nothing;
