-- Migration: Fix and expand players table for full roster management
alter table public.players add column if not exists goals smallint default 0;
alter table public.players add column if not exists assists smallint default 0;
alter table public.players add column if not exists is_captain boolean default false;
alter table public.players add column if not exists nationality text default 'TR';
alter table public.players add column if not exists active_seasons text[] default '{"2026 - Summer League"}';
alter table public.players add column if not exists birth_date date;

alter table public.players alter column team_id drop not null;
alter table public.players alter column id drop identity if exists;
alter table public.players alter column id add generated by default as identity;

alter table public.players enable row level security;
drop policy if exists "players_all_access" on public.players;
create policy "players_all_access" on public.players for all using (true) with check (true);
